### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Delte** [frappe/drive#149]
Haven't been updated last 15 day, latest upgrade gives Build Error.

```
Running build command for drive
warning ../../package.json: No license field
$ cd frontend && npm run build

> frontend@0.0.0 build
> vite build --base=/assets/drive/frontend/ && yarn copy-html-entry

vite v4.5.0 building for production...
transforming (137) src/components/DriveToolBar.vue
Inter-DisplayRegular.woff2?v=3.19 referenced in /home/frappe/frappe-bench/apps/drive/frontend/src/index.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
✓ 239 modules transformed.
✓ built in 13.84s
[vite]: Rollup failed to resolve import "x-data-spreadsheet" from "/home/frappe/frappe-bench/apps/drive/frontend/src/components/FileTypePreview/SheetPreview.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "x-data-spreadsheet" from "/home/frappe/frappe-bench/apps/drive/frontend/src/components/FileTypePreview/SheetPreview.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onRollupWarning (file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
    at onwarn (file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///home/frappe/frappe-bench/apps/drive/frontend/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:451:5)
    at execute (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:128:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5605,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/env/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 72, in build
    bundle(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run build --run-build-command' returned non-zero exit status 1.
```

**Comment by Delte** [comment]
i am using ```bench update --reset``` when i saw its give error on build tried with ```bench build``` and ```bench build --apps drive``` to be sure its from drive
