### ISSUE TITLE
Frappe Cloud - Unable to install Frappe Drive 

### ISSUE THREAD

**Issue by yamenzk** [frappe/drive#155]
Created a new bench on Frappe Cloud and installed Frappe Drive on it.
When I try to deploy it to a site I get the following:

> Installing drive...
An error occurred while installing drive: Module import failed for Drive Entity, the DocType you're trying to open might be deleted.<br> Error: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 241, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
				  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
	   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
	   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/drive/drive/drive/doctype/drive_entity/drive_entity.py", line 6, in <module>
    from drive.utils.files import (
  File "apps/drive/drive/utils/files.py", line 7, in <module>
    import cv2
  File "env/lib/python3.11/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "env/lib/python3.11/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
		    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
	   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
>   File "apps/frappe/frappe/commands/site.py", line 462, in install_app
>     _install_app(app, verbose=context.verbose, force=force)
>   File "apps/frappe/frappe/installer.py", line 301, in install_app
>     sync_for(name, force=force, reset_permissions=True)
>   File "apps/frappe/frappe/model/sync.py", line 111, in sync_for
>     import_file_by_path(
>   File "apps/frappe/frappe/modules/import_file.py", line 148, in import_file_by_path
>     import_doc(
>   File "apps/frappe/frappe/modules/import_file.py", line 245, in import_doc
>     doc.insert()
>   File "apps/frappe/frappe/model/document.py", line 310, in insert
>     self.run_post_save_methods()
>   File "apps/frappe/frappe/model/document.py", line 1118, in run_post_save_methods
>     self.run_method("on_update")
>   File "apps/frappe/frappe/model/document.py", line 950, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
> 	  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "apps/frappe/frappe/model/document.py", line 1316, in composer
>     return composed(self, method, *args, **kwargs)
> 	   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "apps/frappe/frappe/model/document.py", line 1298, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
> 			      ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "apps/frappe/frappe/model/document.py", line 947, in fn
>     return method_object(*args, **kwargs)
> 	   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 526, in on_update
>     self.run_module_method("on_doctype_update")
>   File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 624, in run_module_method
>     module = load_doctype_module(self.name, self.module)
> 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
>     raise ImportError(msg) from e
>     ImportError: Module import failed for Drive Entity, the DocType you're trying to open might be deleted.<br> Error: libGL.so.1: cannot open shared object file: No such file or directory

Running the latest version of everything.

**Comment by rmehta** [comment]
+1
