### ISSUE TITLE
Move and Search not working

### ISSUE THREAD

**Issue by CloudERPng** [frappe/drive#256]
The Search function is not working

Neither is the move function, I am unable to move a folder to a different location

**Comment by CloudERPng** [comment]
Drive version is 0.0.8 develop

**Comment by CloudERPng** [comment]
Still note working 

I get the following error in console when i try to move, and I am the creator of the folder I am trying to move

runtime-core.esm-bundler.js:277 Error: /api/method/drive.api.files.move PermissionError
    at Object.transformResponse (frappeRequest.js:71:17)
    at async Proxy.o (resources.js:103:18)
