### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by CloudERPng** [frappe/drive#261]
The Search function is not working and this makes it extremely difficult if not impossible to use this as a document management system.

Please help look into this

Error in console is shown below

frappeRequest.js:71 Uncaught (in promise) Error: /api/method/drive.api.files.search OperationalError
    at Object.transformResponse (frappeRequest.js:71:17)
    at async Proxy.o (resources.js:103:18)

**Comment by CloudERPng** [comment]
Yes this is the site that was on the old version which has now been updated.

I did what you said and nothing happened, Search is still not working. And i did bench restart and migrate after

**Comment by CloudERPng** [comment]
@uhrjun can you test this and confirm if this is working on your instance ?? It is making the app almost unusable in real life for the users

**Comment by CloudERPng** [comment]
![image](https://github.com/user-attachments/assets/7a69b389-9ec4-4491-9c05-ef9fab68a1d6)

**Comment by CloudERPng** [comment]
I searched with 3 characters and above

**Comment by CloudERPng** [comment]
Just saw this in my error log, does this help?

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
      request = <Request 'https://mybiz.example.com/api/method/drive.api.files.search' [POST]>
      response = None
      rollback = True
      e = OperationalError(1191, "Can't find FULLTEXT index matching the column list")
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
      request = <Request 'https://mybiz.example.com/api/method/drive.api.files.search' [POST]>
      endpoint = <function handle_rpc_call at 0x7fbc6dfcc1f0>
      arguments = {'method': 'drive.api.files.search'}
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
      method = 'drive.api.files.search'
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
      cmd = 'drive.api.files.search'
      data = None
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
      cmd = 'drive.api.files.search'
      from_async = False
      server_script = None
      method = <function search at 0x7fbc58271630>
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
      fn = <function search at 0x7fbc58271630>
      args = ()
      kwargs = {'query': 'Lizz', 'home_dir': '27e6c56296c113121d6715f69815a9fd', 'cmd': 'drive.api.files.search'}
      newargs = {'query': 'Lizz', 'home_dir': '27e6c56296c113121d6715f69815a9fd'}
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
      args = ()
      kwargs = {'query': 'Lizz', 'home_dir': '27e6c56296c113121d6715f69815a9fd'}
      apply_condition = <function whitelist.<locals>.innerfn.<locals>.<lambda> at 0x7fbc582715a0>
      func = <function search at 0x7fbc58271510>
  File "apps/drive/drive/api/files.py", line 1304, in search
    result = frappe.db.sql(
      query = 'Lizz'
      home_dir = '27e6c56296c113121d6715f69815a9fd'
      text = "'Lizz*'"
      user = "'admin@mybiz.com.com'"
      omit = "'27e6c56296c113121d6715f69815a9fd'"
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
      self = <frappe.database.mariadb.database.MariaDBDatabase object at 0x7fbc441e6d10>
      query = "SELECT  `tabDrive Entity`.name,\n            `tabDrive Entity`.title, \n            `tabDrive Entity`.owner,\n            `tabDrive Entity`.mime_type,\n            `tabDrive Entity`.is_group,\n            `tabDrive Entity`.document,\n            `tabDrive Entity`.color,\n            `tabUser`.user_image,\n            `tabUser`.full_name\n    FROM `tabDrive Entity`\n    LEFT JOIN `tabDrive DocShare`\n    ON `tabDrive DocShare`.`share_name` = `tabDrive Entity`.`name`\n    LEFT JOIN `tabUser Group Member`\n    ON `tabUser Group Member`.`parent` = `tabDrive DocShare`.`user_name`\n    LEFT JOIN `tabUser` ON `tabDrive Entity`.`owner` = `tabUser`.`email`\n    WHERE (`tabUser Group Member`.`user` = 'admin@fradrogroup.com' \n            OR `tabDrive DocShare`.`user_name` = 'admin@mybiz.com' \n            OR `tabDrive DocShare`.`everyone` = 1 \n            OR `tabDrive Entity`.`owner` = 'admin@mybiz.com')\n        AND `tabDrive Entity`.`is_active` = 1\n        AND MATCH(title) AGAIN...
      values = None
      as_dict = 1
      as_list = 0
      debug = False
      ignore_ddl = 0
      auto_commit = 0
      update = None
      explain = False
      run = True
      pluck = False
      as_iterator = False
      trace_id = None
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
      self = <pymysql.cursors.Cursor object at 0x7fbc441e5240>
      query = "SELECT  `tabDrive Entity`.name,\n            `tabDrive Entity`.title, \n            `tabDrive Entity`.owner,\n            `tabDrive Entity`.mime_type,\n            `tabDrive Entity`.is_group,\n            `tabDrive Entity`.document,\n            `tabDrive Entity`.color,\n            `tabUser`.user_image,\n            `tabUser`.full_name\n    FROM `tabDrive Entity`\n    LEFT JOIN `tabDrive DocShare`\n    ON `tabDrive DocShare`.`share_name` = `tabDrive Entity`.`name`\n    LEFT JOIN `tabUser Group Member`\n    ON `tabUser Group Member`.`parent` = `tabDrive DocShare`.`user_name`\n    LEFT JOIN `tabUser` ON `tabDrive Entity`.`owner` = `tabUser`.`email`\n    WHERE (`tabUser Group Member`.`user` = 'admin@mybiz.com' \n            OR `tabDrive DocShare`.`user_name` = 'admin@mybiz.com' \n            OR `tabDrive DocShare`.`everyone` = 1 \n            OR `tabDrive Entity`.`owner` = 'admin@mybiz.com')\n        AND `tabDrive Entity`.`is_active` = 1\n        AND MATCH(title) AGAIN...
      args = None
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
      self = <pymysql.cursors.Cursor object at 0x7fbc441e5240>
      q = "SELECT  `tabDrive Entity`.name,\n            `tabDrive Entity`.title, \n            `tabDrive Entity`.owner,\n            `tabDrive Entity`.mime_type,\n            `tabDrive Entity`.is_group,\n            `tabDrive Entity`.document,\n            `tabDrive Entity`.color,\n            `tabUser`.user_image,\n            `tabUser`.full_name\n    FROM `tabDrive Entity`\n    LEFT JOIN `tabDrive DocShare`\n    ON `tabDrive DocShare`.`share_name` = `tabDrive Entity`.`name`\n    LEFT JOIN `tabUser Group Member`\n    ON `tabUser Group Member`.`parent` = `tabDrive DocShare`.`user_name`\n    LEFT JOIN `tabUser` ON `tabDrive Entity`.`owner` = `tabUser`.`email`\n    WHERE (`tabUser Group Member`.`user` = 'admin@mybiz.com' \n            OR `tabDrive DocShare`.`user_name` = 'admin@fradrogroup.com' \n            OR `tabDrive DocShare`.`everyone` = 1 \n            OR `tabDrive Entity`.`owner` = 'admin@fradrogroup.com')\n        AND `tabDrive Entity`.`is_active` = 1\n        AND MATCH(title) AGAIN...
      conn = <pymysql.connections.Connection object at 0x7fbc441e5db0>
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
      self = <pymysql.connections.Connection object at 0x7fbc441e5db0>
      sql = b"SELECT  `tabDrive Entity`.name,\n            `tabDrive Entity`.title, \n            `tabDrive Entity`.owner,\n            `tabDrive Entity`.mime_type,\n            `tabDrive Entity`.is_group,\n            `tabDrive Entity`.document,\n            `tabDrive Entity`.color,\n            `tabUser`.user_image,\n            `tabUser`.full_name\n    FROM `tabDrive Entity`\n    LEFT JOIN `tabDrive DocShare`\n    ON `tabDrive DocShare`.`share_name` = `tabDrive Entity`.`name`\n    LEFT JOIN `tabUser Group Member`\n    ON `tabUser Group Member`.`parent` = `tabDrive DocShare`.`user_name`\n    LEFT JOIN `tabUser` ON `tabDrive Entity`.`owner` = `tabUser`.`email`\n    WHERE (`tabUser Group Member`.`user` = 'admin@mybiz.com' \n            OR `tabDrive DocShare`.`user_name` = 'admin@mybiz.com' \n            OR `tabDrive DocShare`.`everyone` = 1 \n            OR `tabDrive Entity`.`owner` = 'admin@mybiz.com')\n        AND `tabDrive Entity`.`is_active` = 1\n        AND MATCH(title) AGAI...
      unbuffered = False
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
      self = <pymysql.connections.Connection object at 0x7fbc441e5db0>
      unbuffered = False
      result = <pymysql.connections.MySQLResult object at 0x7fbc441e6b90>
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
      self = <pymysql.connections.MySQLResult object at 0x7fbc441e6b90>
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
      self = <pymysql.connections.Connection object at 0x7fbc441e5db0>
      packet_type = <class 'pymysql.protocol.MysqlPacket'>
      buff = bytearray(b"\xff\xa7\x04#HY000Can\'t find FULLTEXT index matching the column list")
      packet_header = b';\x00\x00\x01'
      btrl = 59
      btrh = 0
      packet_number = 1
      bytes_to_read = 59
      recv_data = b"\xff\xa7\x04#HY000Can't find FULLTEXT index matching the column list"
      packet = <pymysql.protocol.MysqlPacket object at 0x7fbc441e4d90>
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
      self = <pymysql.protocol.MysqlPacket object at 0x7fbc441e4d90>
      errno = 1191
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
      data = b"\xff\xa7\x04#HY000Can't find FULLTEXT index matching the column list"
      errno = 1191
      errval = "Can't find FULLTEXT index matching the column list"
      errorclass = <class 'pymysql.err.OperationalError'>
pymysql.err.OperationalError: (1191, "Can't find FULLTEXT index matching the column list")

**Comment by CloudERPng** [comment]
Works perfectly now 

Thanks !!!

**Comment by CloudERPng** [comment]
Fixed!!
