### ISSUE TITLE
FileNotFoundError: User directory does not exist

### ISSUE THREAD

**Issue by iMoshi** [frappe/drive#27]
I've uninstalled and re-installed the app on one of my sites, and now I can't seem to create folders or upload files. I get the following error:

`Traceback (most recent call last):
  File "apps/drive/drive/api/files.py", line 101, in create_folder
    user_directory = get_user_directory()
  File "apps/drive/drive/utils/files.py", line 53, in get_user_directory
    raise FileNotFoundError('User directory does not exist')
FileNotFoundError: User directory does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
  File "apps/drive/drive/api/files.py", line 103, in create_folder
    user_directory = create_user_directory()
  File "apps/drive/drive/utils/files.py", line 19, in create_user_directory
    user_directory_path.mkdir(exist_ok=False)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: 'my.site/private/7b7bc2512ee1fedcd76bdc68926d4f7b'`

Uninstalling the app and re-installing again does not fix the issue. What can I do at this point?

**Comment by iMoshi** [comment]
I'm on v14 of both Frappe / ERPNext if that helps :)

ERPNext: v14.5.1
Frappe: v14.14.2

**Comment by iMoshi** [comment]
Here's a screenshot of my console :) 

https://ibb.co/q0DH6CW
