### ISSUE TITLE
On a fresh install, creating a folder raises Internal Server Error

### ISSUE THREAD

**Issue by agritheory** [frappe/drive#6]
drive 0.0.1
erpnext 13.27.0
frappe 13.26.1

```
16:58:53 web.1            | 127.0.0.1 - - [15/Sep/2022 16:58:53] "POST /api/method/drive.api.files.list_folder_contents HTTP/1.1" 200 -
16:59:00 web.1            | Traceback (most recent call last):
16:59:00 web.1            |   File "apps/frappe/frappe/app.py", line 69, in application
16:59:00 web.1            |     response = frappe.api.handle()
16:59:00 web.1            |   File "apps/frappe/frappe/api.py", line 55, in handle
16:59:00 web.1            |     return frappe.handler.handle()
16:59:00 web.1            |   File "apps/frappe/frappe/handler.py", line 37, in handle
16:59:00 web.1            |     data = execute_cmd(cmd)
16:59:00 web.1            |   File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
16:59:00 web.1            |     return frappe.call(method, **frappe.form_dict)
16:59:00 web.1            |   File "apps/frappe/frappe/__init__.py", line 1447, in call
16:59:00 web.1            |     return fn(*args, **newargs)
16:59:00 web.1            |   File "apps/drive/drive/api/files.py", line 122, in create_folder
16:59:00 web.1            |     drive_entity.share(frappe.session.user, write=1, share=1)
16:59:00 web.1            |   File "apps/drive/drive/drive/doctype/drive_entity/drive_entity.py", line 151, in share
16:59:00 web.1            |     for child in self.get_children():
16:59:00 web.1            | AttributeError: 'DriveEntity' object has no attribute 'get_children'
16:59:00 web.1            |
16:59:00 web.1            | Traceback (most recent call last):
16:59:00 web.1            |   File "apps/frappe/frappe/app.py", line 69, in application
16:59:00 web.1            |     response = frappe.api.handle()
16:59:00 web.1            |   File "apps/frappe/frappe/api.py", line 55, in handle
16:59:00 web.1            |     return frappe.handler.handle()
16:59:00 web.1            |   File "apps/frappe/frappe/handler.py", line 37, in handle
16:59:00 web.1            |     data = execute_cmd(cmd)
16:59:00 web.1            |   File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
16:59:00 web.1            |     return frappe.call(method, **frappe.form_dict)
16:59:00 web.1            |   File "apps/frappe/frappe/__init__.py", line 1447, in call
16:59:00 web.1            |     return fn(*args, **newargs)
16:59:00 web.1            |   File "apps/drive/drive/api/files.py", line 122, in create_folder
16:59:00 web.1            |     drive_entity.share(frappe.session.user, write=1, share=1)
16:59:00 web.1            |   File "apps/drive/drive/drive/doctype/drive_entity/drive_entity.py", line 151, in share
16:59:00 web.1            |     for child in self.get_children():
16:59:00 web.1            | AttributeError: 'DriveEntity' object has no attribute 'get_children'
```

**Comment by krantheman** [comment]
@agritheory sure! I believe this bug does not occur once you upgrade to frappe 14.x.x.

**Comment by agritheory** [comment]
@krantheman Indeed it does. I am opening a PR with a backport.
